-- PHASE-03B: reject authorization, atomic moderation, and shipped-client compatibility.
-- Local candidate only. Do not apply without the separately recorded Stage/Prod gate.
begin;

do $do$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'flag_status'
  ) then
    create type public.flag_status as enum ('open', 'verified', 'resolved', 'rejected');
  end if;
end
$do$;

alter table public.flags
  add column if not exists last_moderation_reason_code text;

alter table public.flags
  drop constraint if exists flags_last_moderation_reason_code_vocabulary;
alter table public.flags
  add constraint flags_last_moderation_reason_code_vocabulary
  check (
    last_moderation_reason_code is null
    or last_moderation_reason_code in (
      'duplicate',
      'not_accessibility_barrier',
      'inaccurate',
      'abusive_or_spam',
      'other',
      'moderator_error',
      'new_evidence',
      'corrected_report'
    )
  );

alter table public.feedback
  add column if not exists moderation_reviewed_at timestamptz,
  add column if not exists moderation_reviewed_by uuid references public.users(id) on delete set null,
  add column if not exists moderation_resolution text,
  add column if not exists moderation_action_intent text,
  add column if not exists moderation_reason_code text;

alter table public.feedback
  drop constraint if exists feedback_moderation_resolution_vocabulary;
alter table public.feedback
  add constraint feedback_moderation_resolution_vocabulary
  check (
    moderation_resolution is null
    or moderation_resolution in (
      'no_action', 'flag_rejected', 'flag_removed', 'comment_removed', 'target_unavailable'
    )
  );

alter table public.feedback
  drop constraint if exists feedback_moderation_action_intent_vocabulary;
alter table public.feedback
  add constraint feedback_moderation_action_intent_vocabulary
  check (
    moderation_action_intent is null
    or moderation_action_intent in ('flag_rejected', 'flag_removed', 'comment_removed')
  );

alter table public.feedback
  drop constraint if exists feedback_moderation_reason_code_vocabulary;
alter table public.feedback
  add constraint feedback_moderation_reason_code_vocabulary
  check (
    moderation_reason_code is null
    or moderation_reason_code in (
      'duplicate', 'not_accessibility_barrier', 'inaccurate', 'abusive_or_spam', 'other'
    )
  );

alter table public.feedback
  drop constraint if exists feedback_moderation_review_pairing;
alter table public.feedback
  add constraint feedback_moderation_review_pairing
  check (
    (moderation_reviewed_at is null and moderation_resolution is null)
    or (moderation_reviewed_at is not null and moderation_resolution is not null)
  );

alter table public.feedback
  drop constraint if exists feedback_reject_reason_pairing;
alter table public.feedback
  add constraint feedback_reject_reason_pairing
  check (
    (moderation_resolution = 'flag_rejected' and moderation_reason_code is not null)
    or (moderation_resolution is distinct from 'flag_rejected' and moderation_reason_code is null)
  );

create index if not exists feedback_moderation_open_idx
  on public.feedback (created_at)
  where moderation_reviewed_at is null and body like '[REPORT]%';

create table if not exists public.flag_moderation_events (
  id bigint generated by default as identity primary key,
  flag_id uuid not null,
  actor_id uuid references public.users(id) on delete set null,
  action text not null check (action in ('reject', 'restore')),
  reason_code text not null,
  from_status text not null,
  to_status text not null,
  report_id uuid,
  reverses_event_id bigint references public.flag_moderation_events(id),
  created_at timestamptz not null default now(),
  constraint flag_moderation_events_transition check (
    (action = 'reject'
      and from_status in ('open', 'verified', 'resolved')
      and to_status = 'rejected'
      and reason_code in (
        'duplicate', 'not_accessibility_barrier', 'inaccurate', 'abusive_or_spam', 'other'
      )
      and reverses_event_id is null)
    or
    (action = 'restore'
      and from_status = 'rejected'
      and to_status = 'open'
      and reason_code in ('moderator_error', 'new_evidence', 'corrected_report', 'other'))
  )
);

create unique index if not exists flag_moderation_events_one_reversal_idx
  on public.flag_moderation_events (reverses_event_id)
  where reverses_event_id is not null;
create index if not exists flag_moderation_events_flag_created_idx
  on public.flag_moderation_events (flag_id, created_at desc, id desc);
create unique index if not exists flag_moderation_events_report_reject_idx
  on public.flag_moderation_events (report_id)
  where report_id is not null and action = 'reject';

alter table public.flag_moderation_events enable row level security;
revoke all on table public.flag_moderation_events from public, anon, authenticated, service_role;
revoke all on sequence public.flag_moderation_events_id_seq from public, anon, authenticated, service_role;
grant select on table public.flag_moderation_events to authenticated;

drop policy if exists "flag moderation events admin read" on public.flag_moderation_events;
create policy "flag moderation events admin read"
  on public.flag_moderation_events for select
  to authenticated
  using ((select private.current_user_is_admin()));

create or replace function private.reject_flag_moderation_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
  raise exception 'flag moderation events are append-only' using errcode = '42501';
end
$fn$;

revoke all on function private.reject_flag_moderation_event_mutation()
  from public, anon, authenticated, service_role;

drop trigger if exists flag_moderation_events_immutable on public.flag_moderation_events;
create trigger flag_moderation_events_immutable
  before update or delete on public.flag_moderation_events
  for each row execute function private.reject_flag_moderation_event_mutation();

-- A rejected flag is absent from default/public reads regardless of which
-- permissive policy admitted the row. Admins retain recovery visibility.
drop policy if exists "flags rejected hidden from anon" on public.flags;
create policy "flags rejected hidden from anon"
  on public.flags as restrictive for select
  to anon
  using (status <> 'rejected');

drop policy if exists "flags rejected hidden from nonadmins" on public.flags;
create policy "flags rejected hidden from nonadmins"
  on public.flags as restrictive for select
  to authenticated
  using (status <> 'rejected' or (select private.current_user_is_admin()));

drop policy if exists "flags insert status open only" on public.flags;
create policy "flags insert status open only"
  on public.flags as restrictive for insert
  to anon, authenticated
  with check (status = 'open');

-- The inherited owner-edit policy queried public.flags from inside a policy on
-- public.flags. Once direct status permission is retained, PostgreSQL evaluates
-- that recursive policy and the shipped PATCH fails with 42P17 even though the
-- separate community-status policy admits the row. Column grants already keep
-- immutable coordinates/ownership fields out of the owner edit surface, so use
-- a non-recursive owner predicate here.
drop policy if exists "flags owner edit open" on public.flags;
create policy "flags owner edit open"
  on public.flags for update
  to authenticated
  using ((select auth.uid()) = user_id and status = 'open')
  with check ((select auth.uid()) = user_id);

-- Build 33 and the pinned production web client still issue a direct
-- PostgREST UPDATE(status) with an expected-status filter. Keep that exact
-- compatibility surface until those clients are retired. The transition
-- trigger below remains the authority for the allowed community transitions,
-- and the compatibility guard forces reject/restore through the audited RPC.
-- Other owner edit columns retain their existing grants and policies.
revoke update (status) on public.flags from public, anon;
grant update (status) on public.flags to authenticated;
revoke update (last_moderation_reason_code) on public.flags from public, anon, authenticated;

-- Moderation columns are server-managed through the two RPCs below.
revoke update (
  moderation_reviewed_at,
  moderation_reviewed_by,
  moderation_resolution,
  moderation_action_intent,
  moderation_reason_code
) on public.feedback from public, anon, authenticated;

drop policy if exists "feedback_select_report_requires_admin" on public.feedback;
create policy "feedback_select_report_requires_admin"
  on public.feedback as restrictive for select
  to authenticated
  using (
    body not like '[REPORT]%'
    or (select private.current_user_is_admin())
  );

-- Edge status notifications must honor the reporter's existing preference,
-- but Phase03A intentionally removed service_role's direct table access.
-- Expose exactly one boolean through an owner-executed RPC; no preference row
-- or unrelated user data crosses the API boundary.
create or replace function public.flag_status_notifications_enabled(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select coalesce(
    (
      select preference.flag_status_updates
      from public.notification_preferences preference
      where preference.user_id = p_user_id
    ),
    true
  )
$fn$;

revoke all on function public.flag_status_notifications_enabled(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.flag_status_notifications_enabled(uuid)
  to service_role;

create or replace function public.enforce_flag_status_transition()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
begin
  if new.status = old.status then
    return new;
  end if;

  if (old.status = 'open' and new.status in ('verified', 'resolved'))
     or (old.status = 'verified' and new.status = 'resolved')
     or (old.status = 'resolved' and new.status = 'open')
  then
    return new;
  end if;

  if (
       (old.status in ('open', 'verified', 'resolved') and new.status = 'rejected')
       or (old.status = 'rejected' and new.status = 'open')
     )
     and coalesce((select private.current_user_is_admin()), false)
  then
    return new;
  end if;

  raise exception 'illegal flag status transition: % -> %', old.status, new.status
    using errcode = 'P0001';
end
$fn$;

revoke all on function public.enforce_flag_status_transition()
  from public, anon, authenticated, service_role;

-- The temporary direct-write bridge is deliberately narrower than the RPC.
-- SECURITY DEFINER execution of transition_flag_status() retains the function
-- owner's current_user while a direct PostgREST write runs as authenticated;
-- the RPC also supplies a transaction-local actor marker only around its own
-- update. Requiring both lets shipped clients keep verify/resolve/reopen without
-- creating an unaudited admin-only reject/restore path.
create or replace function public.enforce_flag_status_compatibility_bridge()
returns trigger
language plpgsql
set search_path = ''
as $fn$
declare
  v_transition_owner name;
  v_rpc_actor text;
begin
  if new.status = old.status then
    return new;
  end if;

  if (old.status in ('open', 'verified', 'resolved') and new.status = 'rejected')
     or (old.status = 'rejected' and new.status = 'open')
  then
    select pg_catalog.pg_get_userbyid(proc.proowner)::name
      into v_transition_owner
      from pg_catalog.pg_proc proc
     where proc.oid =
       'public.transition_flag_status(uuid,public.flag_status,public.flag_status,text,uuid)'::pg_catalog.regprocedure;

    v_rpc_actor := nullif(
      pg_catalog.current_setting('flagstone.phase03b_transition_actor', true),
      ''
    );

    if current_user::name is distinct from v_transition_owner
       or v_rpc_actor is distinct from (select auth.uid())::text
    then
      raise exception 'Reject and restore require the audited status RPC.'
        using errcode = '42501';
    end if;
  end if;

  return new;
end
$fn$;

revoke all on function public.enforce_flag_status_compatibility_bridge()
  from public, anon, authenticated, service_role;

drop trigger if exists flag_status_transition_guard on public.flags;
create trigger flag_status_transition_guard
  before update of status on public.flags
  for each row execute function public.enforce_flag_status_transition();

drop trigger if exists flag_status_compatibility_bridge_guard on public.flags;
create trigger flag_status_compatibility_bridge_guard
  before update of status on public.flags
  for each row execute function public.enforce_flag_status_compatibility_bridge();

create or replace function public.transition_flag_status(
  p_flag_id uuid,
  p_expected_status public.flag_status,
  p_new_status public.flag_status,
  p_moderation_reason text default null,
  p_report_id uuid default null
)
returns setof public.flags
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor uuid := (select auth.uid());
  v_is_admin boolean := false;
  v_flag public.flags%rowtype;
  v_updated public.flags%rowtype;
  v_reversed_event_id bigint;
  v_reason text := nullif(btrim(p_moderation_reason), '');
  v_did_update boolean;
begin
  if v_actor is null
     or not exists (select 1 from public.users account where account.id = v_actor)
  then
    raise exception 'Account is no longer active.' using errcode = '42501';
  end if;

  select coalesce(account.is_admin, false)
    into v_is_admin
    from public.users account
    where account.id = v_actor;

  select * into v_flag
    from public.flags
    where id = p_flag_id
    for update;

  if not found then
    raise exception 'Flag not found.' using errcode = 'P0002';
  end if;

  if v_flag.status <> p_expected_status::text then
    raise exception 'This flag changed since you opened it. Refresh and try again.'
      using errcode = 'P0001';
  end if;

  if p_expected_status = p_new_status then
    raise exception 'The requested status is already current.' using errcode = 'P0001';
  end if;

  if p_report_id is not null
     and not exists (
       select 1 from public.feedback report
       where report.id = p_report_id
         and report.body like '[REPORT]%'
         and report.moderation_reviewed_at is null
     )
  then
    raise exception 'The moderation report is missing or already closed.' using errcode = 'P0002';
  end if;

  if p_new_status = 'rejected'::public.flag_status then
    if not v_is_admin then
      raise exception 'Only Flagstone admins can reject reports.' using errcode = '42501';
    end if;
    if p_expected_status not in (
      'open'::public.flag_status, 'verified'::public.flag_status, 'resolved'::public.flag_status
    ) then
      raise exception 'A rejected report cannot be rejected again.' using errcode = 'P0001';
    end if;
    if v_reason is null or v_reason not in (
      'duplicate', 'not_accessibility_barrier', 'inaccurate', 'abusive_or_spam', 'other'
    ) then
      raise exception 'A valid rejection reason is required.' using errcode = '22023';
    end if;
  elsif p_expected_status = 'rejected'::public.flag_status
        and p_new_status = 'open'::public.flag_status then
    if not v_is_admin then
      raise exception 'Only Flagstone admins can restore reports.' using errcode = '42501';
    end if;
    if v_reason is null or v_reason not in (
      'moderator_error', 'new_evidence', 'corrected_report', 'other'
    ) then
      raise exception 'A valid restoration reason is required.' using errcode = '22023';
    end if;
  else
    if v_reason is not null or p_report_id is not null then
      raise exception 'Moderation metadata is only valid for reject or restore.' using errcode = '22023';
    end if;
  end if;

  -- The transaction-local marker and SECURITY DEFINER owner check are both
  -- required by the compatibility trigger. Neither a direct client role nor an
  -- unrelated owner-executed function can impersonate this moderation call.
  perform pg_catalog.set_config(
    'flagstone.phase03b_transition_actor',
    v_actor::text,
    true
  );

  update public.flags
     set status = p_new_status::text,
         last_moderation_reason_code = case
           when p_new_status = 'rejected'::public.flag_status
             or p_expected_status = 'rejected'::public.flag_status
           then v_reason
           else null
         end
   where id = p_flag_id
     and status = p_expected_status::text
   returning * into v_updated;

  v_did_update := found;
  perform pg_catalog.set_config('flagstone.phase03b_transition_actor', '', true);

  if not v_did_update then
    raise exception 'This flag changed since you opened it. Refresh and try again.'
      using errcode = 'P0001';
  end if;

  if p_new_status = 'rejected'::public.flag_status then
    insert into public.flag_moderation_events (
      flag_id, actor_id, action, reason_code, from_status, to_status, report_id
    ) values (
      p_flag_id, v_actor, 'reject', v_reason,
      p_expected_status::text, p_new_status::text, p_report_id
    );
  elsif p_expected_status = 'rejected'::public.flag_status
        and p_new_status = 'open'::public.flag_status then
    -- Pre-Phase03B rejected rows have no moderation event to link. They are
    -- still recoverable, but the new restore row deliberately keeps
    -- reverses_event_id NULL rather than inventing a historical rejection.
    select event.id into v_reversed_event_id
      from public.flag_moderation_events event
      where event.flag_id = p_flag_id
        and event.action = 'reject'
        and not exists (
          select 1 from public.flag_moderation_events recovery
          where recovery.reverses_event_id = event.id
        )
      order by event.created_at desc, event.id desc
      limit 1;

    insert into public.flag_moderation_events (
      flag_id, actor_id, action, reason_code, from_status, to_status,
      report_id, reverses_event_id
    ) values (
      p_flag_id, v_actor, 'restore', v_reason,
      p_expected_status::text, p_new_status::text, p_report_id, v_reversed_event_id
    );
  end if;

  return next v_updated;
end
$fn$;

revoke all on function public.transition_flag_status(
  uuid, public.flag_status, public.flag_status, text, uuid
) from public, anon, authenticated, service_role;
grant execute on function public.transition_flag_status(
  uuid, public.flag_status, public.flag_status, text, uuid
) to authenticated;

create or replace function public.list_open_moderation_reports(p_limit integer default 100)
returns table (
  id uuid,
  created_at timestamptz,
  body text,
  moderation_reviewed_at timestamptz,
  moderation_resolution text,
  moderation_action_intent text
)
language plpgsql
stable
security definer
set search_path = ''
as $fn$
begin
  if (select auth.uid()) is null
     or not coalesce((select private.current_user_is_admin()), false)
  then
    raise exception 'Only Flagstone admins can read moderation reports.' using errcode = '42501';
  end if;

  return query
    select report.id,
           report.created_at,
           report.body,
           report.moderation_reviewed_at,
           report.moderation_resolution,
           report.moderation_action_intent
      from public.feedback report
     where report.body like '[REPORT]%'
       and report.moderation_reviewed_at is null
     order by report.created_at asc, report.id asc
     limit greatest(1, least(coalesce(p_limit, 100), 200));
end
$fn$;

revoke all on function public.list_open_moderation_reports(integer)
  from public, anon, authenticated, service_role;
grant execute on function public.list_open_moderation_reports(integer)
  to authenticated;

create or replace function public.moderate_report(
  p_report_id uuid,
  p_resolution text,
  p_expected_flag_status public.flag_status default null,
  p_moderation_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor uuid := (select auth.uid());
  v_report public.feedback%rowtype;
  v_header text;
  v_match text[];
  v_target_kind text;
  v_target_id uuid;
  v_parent_flag_id uuid;
  v_reason text := nullif(btrim(p_moderation_reason), '');
  v_target_exists boolean;
  v_flag_has_storage boolean;
begin
  if v_actor is null
     or not coalesce((select private.current_user_is_admin()), false)
  then
    raise exception 'Only Flagstone admins can moderate reports.' using errcode = '42501';
  end if;

  if p_resolution not in (
    'no_action', 'flag_rejected', 'flag_removed', 'comment_removed', 'target_unavailable'
  ) then
    raise exception 'Unknown moderation resolution.' using errcode = '22023';
  end if;

  select * into v_report
    from public.feedback
    where id = p_report_id
    for update;

  if not found then
    raise exception 'Moderation report not found.' using errcode = 'P0002';
  end if;
  if v_report.moderation_reviewed_at is not null then
    if v_report.moderation_resolution = p_resolution
       and v_report.moderation_reason_code is not distinct from v_reason
    then
      return jsonb_build_object(
        'report_id', p_report_id,
        'resolution', v_report.moderation_resolution,
        'already_closed', true
      );
    end if;
    raise exception 'This moderation report was already closed with a different decision.'
      using errcode = 'P0001';
  end if;

  if v_report.body not like '[REPORT]%' then
    raise exception 'The feedback row is not a moderation report.' using errcode = '22023';
  end if;

  -- Malformed/future report envelopes are intentionally visible in the admin
  -- queue. An admin may close one as no_action without pretending its target
  -- was parsed. Every target-mutating resolution still requires the exact
  -- anchored v1/v2 envelope below.
  if p_resolution = 'no_action' then
    if v_reason is not null or p_expected_flag_status is not null then
      raise exception 'No-action does not accept reject metadata.' using errcode = '22023';
    end if;

    update public.feedback
       set moderation_reviewed_at = now(),
           moderation_reviewed_by = v_actor,
           moderation_resolution = 'no_action',
           moderation_action_intent = null,
           moderation_reason_code = null
     where id = p_report_id;

    return jsonb_build_object(
      'report_id', p_report_id,
      'resolution', 'no_action',
      'target_kind', null,
      'target_id', null,
      'already_closed', false
    );
  end if;

  v_header := split_part(v_report.body, E'\n', 1);
  v_match := regexp_match(
    v_header,
    '^\[REPORT\] v(1|2) target=(flag|comment) id=([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})(?: flag=([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}))?(?: cat=[^ ]+)?$'
  );
  if v_match is null or position(E'\n' in v_report.body) = 0 then
    raise exception 'Malformed moderation report envelope.' using errcode = '22023';
  end if;

  v_target_kind := v_match[2];
  v_target_id := v_match[3]::uuid;
  v_parent_flag_id := nullif(v_match[4], '')::uuid;

  if v_target_kind = 'flag' and v_parent_flag_id is not null then
    raise exception 'Malformed flag report envelope.' using errcode = '22023';
  end if;
  -- `flag=` is optional for supported v1/v2 comment envelopes. The target
  -- comment id is authoritative; older and minimal clients did not include a
  -- parent flag id, and those reports must remain actionable.
  if v_target_kind = 'comment'
     and v_parent_flag_id is not null
     and exists (select 1 from public.flag_comments where id = v_target_id)
     and not exists (
       select 1 from public.flag_comments
       where id = v_target_id and flag_id = v_parent_flag_id
     )
  then
    raise exception 'Comment report parent flag does not match target.' using errcode = '22023';
  end if;

  if p_resolution = 'flag_rejected' then
    if v_target_kind <> 'flag' or p_expected_flag_status is null then
      raise exception 'Reject requires a flag report and expected status.' using errcode = '22023';
    end if;
    perform * from public.transition_flag_status(
      v_target_id,
      p_expected_flag_status,
      'rejected'::public.flag_status,
      v_reason,
      p_report_id
    );
  elsif p_resolution = 'flag_removed' then
    if v_target_kind <> 'flag' then
      raise exception 'Flag removal requires a flag report.' using errcode = '22023';
    end if;
    if v_reason is not null or p_expected_flag_status is not null then
      raise exception 'Flag removal does not accept reject metadata.' using errcode = '22023';
    end if;

    select (
      flag.photo_url is not null
      or flag.photo_object_key is not null
      or exists (
        select 1 from public.flag_photos photo where photo.flag_id = flag.id
      )
    ) into v_flag_has_storage
      from public.flags flag
      where flag.id = v_target_id
      for update;

    if not found then
      raise exception 'The reported flag is no longer available.' using errcode = 'P0002';
    end if;
    if v_flag_has_storage then
      raise exception 'Flag removal requires the canonical storage-safe deletion route.'
        using errcode = '55000';
    end if;
    delete from public.flags where id = v_target_id;
  elsif p_resolution = 'comment_removed' then
    if v_target_kind <> 'comment' then
      raise exception 'Comment removal requires a comment report.' using errcode = '22023';
    end if;
    if v_reason is not null or p_expected_flag_status is not null then
      raise exception 'Comment removal does not accept reject metadata.' using errcode = '22023';
    end if;
    delete from public.flag_comments where id = v_target_id;
    if not found then
      raise exception 'The reported comment is no longer available.' using errcode = 'P0002';
    end if;
  elsif p_resolution = 'target_unavailable' then
    if v_target_kind = 'flag' then
      select exists(select 1 from public.flags where id = v_target_id) into v_target_exists;
    else
      select exists(select 1 from public.flag_comments where id = v_target_id) into v_target_exists;
    end if;
    if v_target_exists then
      raise exception 'The reported target is still available.' using errcode = 'P0001';
    end if;
    if v_reason is not null or p_expected_flag_status is not null then
      raise exception 'Target-unavailable does not accept reject metadata.' using errcode = '22023';
    end if;
  end if;

  update public.feedback
     set moderation_reviewed_at = now(),
         moderation_reviewed_by = v_actor,
         moderation_resolution = p_resolution,
         moderation_action_intent = case
           when p_resolution in ('flag_rejected', 'flag_removed', 'comment_removed')
             then p_resolution
           else null
         end,
         moderation_reason_code = case
           when p_resolution = 'flag_rejected' then v_reason
           else null
         end
   where id = p_report_id;

  return jsonb_build_object(
    'report_id', p_report_id,
    'resolution', p_resolution,
    'target_kind', v_target_kind,
    'target_id', v_target_id,
    'already_closed', false
  );
end
$fn$;

revoke all on function public.moderate_report(
  uuid, text, public.flag_status, text
) from public, anon, authenticated, service_role;
grant execute on function public.moderate_report(
  uuid, text, public.flag_status, text
) to authenticated;

commit;
