-- FORWARD RESTORATION of 20260905055633_phase03a_contextual_profiles.
-- Generated by scripts/canonical-migration-identity.mjs (STAGE-MF-08).
--
-- Undoes 20260905055633_phase03a_contextual_profiles.sql. This is a NEW forward migration with its own canonical
-- version (20260912000500), NOT a deletion or rewrite of that candidate's
-- ledger row. After applying this, the ledger truthfully reads: the candidate ran,
-- and was then deliberately undone. Re-applying later is another new forward
-- version, never a re-run of the original.
--
-- Reason: Phase 03A forward-only restoration rehearsal on disposable staging branch cepayqmsoqxshsiyqnvz
--
-- This restores the pre-candidate posture and therefore restores whatever
-- weaknesses that posture had. That is the point of a rollback, and it must be a
-- deliberate decision rather than a reflex.
-- Requires accepted Phase 02 applied + adoption baseline. No production change.
-- Exact order/hashes and outstanding gates are declared in candidate-contract.json.
-- Forward restoration to the pre-03A posture; this restores known weaknesses.
-- Disposable rehearsal only until a separate exact production token authorizes it.
BEGIN;
-- NOTE: this rollback no longer re-creates "users readable by authenticated" and
-- no longer re-grants SELECT (is_admin). Stage A does not remove them -- that
-- moved to 20260911130000_phase03a_fda026_stage_b_cutover.sql, which carries its
-- own rollback. Re-creating the policy here would raise "policy already exists"
-- and abort the whole restoration, because the policy is still present.
ALTER POLICY "admin delete any flag" ON public.flags
USING ((SELECT users.is_admin FROM public.users WHERE users.id = (SELECT auth.uid())));
ALTER POLICY "admin delete any comment" ON public.flag_comments
USING ((SELECT users.is_admin FROM public.users WHERE users.id = (SELECT auth.uid())));
ALTER POLICY "flag-photos admin delete" ON storage.objects
USING (bucket_id = 'flag-photos' AND (SELECT is_admin FROM public.users WHERE id = (SELECT auth.uid())));
DROP FUNCTION public.current_user_can_admin(), public.list_public_leaderboard(integer),
  public.get_my_leaderboard_rank(), public.get_comment_author_profiles(uuid[]);
DROP FUNCTION private.list_public_leaderboard(integer), private.get_my_leaderboard_rank(),
  private.get_comment_author_profiles(uuid[]);
COMMIT;
