-- FORWARD RESTORATION of 20260904000100_drop_duplicate_status_triggers.
-- Generated by scripts/canonical-migration-identity.mjs (STAGE-MF-08).
--
-- Undoes 20260904000100_drop_duplicate_status_triggers.sql. This is a NEW forward migration with its own canonical
-- version (20260916001000), NOT a deletion or rewrite of that candidate's
-- ledger row. After applying this, the ledger truthfully reads: the candidate ran,
-- and was then deliberately undone. Re-applying later is another new forward
-- version, never a re-run of the original.
--
-- Reason: Production Phase 03A preflight evidence only; execution requires a separate exact owner authorization and security review.
--
-- This restores the pre-candidate posture and therefore restores whatever
-- weaknesses that posture had. That is the point of a rollback, and it must be a
-- deliberate decision rather than a reflex.
-- Forward restoration for 20260904000100.
--
-- WARNING: recreating this trigger restores the DOUBLE-POINTS defect. It exists
-- only so the rollback set is complete and rehearsable. There is no scenario in
-- which running it is desirable; if a rollback is ever needed, prefer leaving
-- the duplicate dropped and reverting the caller instead.

create trigger trigger_flag_status_change
  after update of status on public.flags
  for each row
  execute function public.handle_flag_status_change();
