-- FORWARD RESTORATION of 20260904000300_adopt_live_insert_throttles.
-- Generated by scripts/canonical-migration-identity.mjs (STAGE-MF-08).
--
-- Undoes 20260904000300_adopt_live_insert_throttles.sql. This is a NEW forward migration with its own canonical
-- version (20260916000800), NOT a deletion or rewrite of that candidate's
-- ledger row. After applying this, the ledger truthfully reads: the candidate ran,
-- and was then deliberately undone. Re-applying later is another new forward
-- version, never a re-run of the original.
--
-- Reason: Production Phase 03A preflight evidence only; execution requires a separate exact owner authorization and security review.
--
-- This restores the pre-candidate posture and therefore restores whatever
-- weaknesses that posture had. That is the point of a rollback, and it must be a
-- deliberate decision rather than a reflex.
-- Forward restoration for 20260904000300.
--
-- WARNING: dropping these removes SERVER-SIDE INSERT THROTTLING, including the
-- only global cap on anonymous reporting. Against production this would open
-- the exact hole a prior audit wrongly believed already existed. It exists for
-- rollback completeness only and must never run without Sky's explicit
-- authorization.

drop trigger if exists enforce_global_anon_rate_limit on public.flags;
drop trigger if exists enforce_flag_rate_limit on public.flags;
drop function if exists public.check_global_anon_rate_limit();
drop function if exists public.check_flag_rate_limit();
grant execute on function public.check_flag_creation_rate_limit()
  to public, anon, authenticated;
