-- FORWARD RESTORATION of 20260904000000_adopt_private_admin_helper.
-- Generated by scripts/canonical-migration-identity.mjs (STAGE-MF-08).
--
-- Undoes 20260904000000_adopt_private_admin_helper.sql. This is a NEW forward migration with its own canonical
-- version (20260916001100), NOT a deletion or rewrite of that candidate's
-- ledger row. After applying this, the ledger truthfully reads: the candidate ran,
-- and was then deliberately undone. Re-applying later is another new forward
-- version, never a re-run of the original.
--
-- Reason: Production Phase 03A preflight evidence only; execution requires a separate exact owner authorization and security review.
--
-- This restores the pre-candidate posture and therefore restores whatever
-- weaknesses that posture had. That is the point of a rollback, and it must be a
-- deliberate decision rather than a reflex.
-- Forward restoration for 20260904000000. Never a history rewrite.
-- Restores the pre-adoption policy shape (the repository's inline-subquery
-- variant) and removes the helper. Only meaningful on a database that did NOT
-- already have the helper — against production this would REMOVE a live,
-- load-bearing object, so it must never be run there without Sky's explicit
-- authorization and a fresh catalog capture first.

drop policy if exists "users update own row" on public.users;
create policy "users update own row"
  on public.users
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check (
    (select auth.uid()) = id
    and is_admin is not distinct from
      (select is_admin from public.users where id = (select auth.uid()))
  );

drop function if exists private.current_user_is_admin();
drop schema if exists private;
