-- FORWARD RESTORATION of 20260905055630_phase03a_open_inserts.
-- Generated by scripts/canonical-migration-identity.mjs (STAGE-MF-08).
--
-- Undoes 20260905055630_phase03a_open_inserts.sql. This is a NEW forward migration with its own canonical
-- version (20260916000600), NOT a deletion or rewrite of that candidate's
-- ledger row. After applying this, the ledger truthfully reads: the candidate ran,
-- and was then deliberately undone. Re-applying later is another new forward
-- version, never a re-run of the original.
--
-- Reason: Production Phase 03A preflight evidence only; execution requires a separate exact owner authorization and security review.
--
-- This restores the pre-candidate posture and therefore restores whatever
-- weaknesses that posture had. That is the point of a rollback, and it must be a
-- deliberate decision rather than a reflex.
-- Requires accepted Phase 02 applied + adoption baseline. No production change.
-- Exact order/hashes and outstanding gates are declared in candidate-contract.json.
-- Forward restoration to the pre-03A posture; this restores known weaknesses.
-- Disposable rehearsal only until a separate exact production token authorizes it.
BEGIN;
DROP POLICY "flags authenticated insert open" ON public.flags;
COMMIT;
