-- FDA-012 effective application privileges. UNACCEPTED LOCAL CANDIDATE.
-- Seventh step after the six preserved Phase03A artifacts. No production authority.
-- Object owner stays postgres; managed supabase_admin defaults are an explicit residual.
-- UNSAFE_BASELINE_RESTORE: recreates excess grants for disposable rehearsal only.
BEGIN;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_comments"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."bk_2026_08_22_flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."bk_2026_08_22_flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."bk_2026_08_22_flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."bk_2026_08_22_flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_edit_history"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."bk_2026_08_22_flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."bk_2026_08_22_flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."bk_2026_08_22_flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."bk_2026_08_22_flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_photos"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("alt_text", "created_at", "flag_id", "id", "position", "url") ON TABLE "public"."bk_2026_08_22_flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("alt_text", "created_at", "flag_id", "id", "position", "url") ON TABLE "public"."bk_2026_08_22_flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("alt_text", "created_at", "flag_id", "id", "position", "url") ON TABLE "public"."bk_2026_08_22_flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("alt_text", "created_at", "flag_id", "id", "position", "url") ON TABLE "public"."bk_2026_08_22_flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_status_history"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."bk_2026_08_22_flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."bk_2026_08_22_flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."bk_2026_08_22_flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."bk_2026_08_22_flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_verifications"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."bk_2026_08_22_flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."bk_2026_08_22_flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."bk_2026_08_22_flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."bk_2026_08_22_flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flags"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_flags" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."bk_2026_08_22_flags" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."bk_2026_08_22_flags" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."bk_2026_08_22_flags" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."bk_2026_08_22_flags" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_point_links"') IS NOT NULL THEN
    REVOKE ALL ON TABLE "public"."bk_2026_08_22_point_links" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE SELECT ("flag_id", "point_event_id") ON TABLE "public"."bk_2026_08_22_point_links" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE INSERT ("flag_id", "point_event_id") ON TABLE "public"."bk_2026_08_22_point_links" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE UPDATE ("flag_id", "point_event_id") ON TABLE "public"."bk_2026_08_22_point_links" FROM PUBLIC, "anon", "authenticated", "service_role";
    REVOKE REFERENCES ("flag_id", "point_event_id") ON TABLE "public"."bk_2026_08_22_point_links" FROM PUBLIC, "anon", "authenticated", "service_role";
  END IF;
END $backup$;
REVOKE ALL ON TABLE "public"."comment_votes" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("comment_id", "created_at", "voter_id") ON TABLE "public"."comment_votes" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("comment_id", "created_at", "voter_id") ON TABLE "public"."comment_votes" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("comment_id", "created_at", "voter_id") ON TABLE "public"."comment_votes" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("comment_id", "created_at", "voter_id") ON TABLE "public"."comment_votes" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."feedback" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("body", "category", "contact_email", "created_at", "id", "platform", "user_id") ON TABLE "public"."feedback" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("body", "category", "contact_email", "created_at", "id", "platform", "user_id") ON TABLE "public"."feedback" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("body", "category", "contact_email", "created_at", "id", "platform", "user_id") ON TABLE "public"."feedback" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("body", "category", "contact_email", "created_at", "id", "platform", "user_id") ON TABLE "public"."feedback" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("content", "created_at", "flag_id", "id", "user_id") ON TABLE "public"."flag_comments" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values", "user_id") ON TABLE "public"."flag_edit_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_edit_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values") ON TABLE "public"."flag_edit_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values") ON TABLE "public"."flag_edit_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values") ON TABLE "public"."flag_edit_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("changed_fields", "created_at", "flag_id", "id", "new_values", "old_values") ON TABLE "public"."flag_edit_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("alt_text", "created_at", "flag_id", "id", "object_key", "position", "url") ON TABLE "public"."flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("alt_text", "created_at", "flag_id", "id", "object_key", "position", "url") ON TABLE "public"."flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("alt_text", "created_at", "flag_id", "id", "object_key", "position", "url") ON TABLE "public"."flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("alt_text", "created_at", "flag_id", "id", "object_key", "position", "url") ON TABLE "public"."flag_photos" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("created_at", "flag_id", "from_status", "id", "to_status", "user_id") ON TABLE "public"."flag_status_history" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_status_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("created_at", "flag_id", "from_status", "id", "to_status") ON TABLE "public"."flag_status_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("created_at", "flag_id", "from_status", "id", "to_status") ON TABLE "public"."flag_status_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("created_at", "flag_id", "from_status", "id", "to_status") ON TABLE "public"."flag_status_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("created_at", "flag_id", "from_status", "id", "to_status") ON TABLE "public"."flag_status_history_public" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("created_at", "flag_id", "id", "verifier_id", "weight") ON TABLE "public"."flag_verifications" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."flags" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_object_key", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."flags" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_object_key", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."flags" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_object_key", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."flags" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("category", "context_tags", "created_at", "description", "dispute_requests", "dispute_requests_reset_at", "id", "lat", "lng", "photo_alt", "photo_object_key", "photo_url", "reopen_requests", "reopen_requests_reset_at", "severity", "status", "updated_at", "user_id") ON TABLE "public"."flags" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."notification_preferences" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("bulk_watch_alerts", "flag_status_updates", "nearby_flags", "updated_at", "user_id", "watched_flag_updates") ON TABLE "public"."notification_preferences" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("bulk_watch_alerts", "flag_status_updates", "nearby_flags", "updated_at", "user_id", "watched_flag_updates") ON TABLE "public"."notification_preferences" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("bulk_watch_alerts", "flag_status_updates", "nearby_flags", "updated_at", "user_id", "watched_flag_updates") ON TABLE "public"."notification_preferences" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("bulk_watch_alerts", "flag_status_updates", "nearby_flags", "updated_at", "user_id", "watched_flag_updates") ON TABLE "public"."notification_preferences" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."point_events" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("created_at", "delta", "event_type", "flag_id", "id", "user_id") ON TABLE "public"."point_events" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("created_at", "delta", "event_type", "flag_id", "id", "user_id") ON TABLE "public"."point_events" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("created_at", "delta", "event_type", "flag_id", "id", "user_id") ON TABLE "public"."point_events" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("created_at", "delta", "event_type", "flag_id", "id", "user_id") ON TABLE "public"."point_events" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."push_tokens" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("created_at", "platform", "token", "updated_at", "user_id") ON TABLE "public"."push_tokens" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("created_at", "platform", "token", "updated_at", "user_id") ON TABLE "public"."push_tokens" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("created_at", "platform", "token", "updated_at", "user_id") ON TABLE "public"."push_tokens" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("created_at", "platform", "token", "updated_at", "user_id") ON TABLE "public"."push_tokens" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."realtime_subscribe_log" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("channel", "event", "id", "logged_at", "user_id") ON TABLE "public"."realtime_subscribe_log" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("channel", "event", "id", "logged_at", "user_id") ON TABLE "public"."realtime_subscribe_log" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("channel", "event", "id", "logged_at", "user_id") ON TABLE "public"."realtime_subscribe_log" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("channel", "event", "id", "logged_at", "user_id") ON TABLE "public"."realtime_subscribe_log" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."users" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("avatar_object_key", "avatar_url", "created_at", "display_name", "email", "id", "is_admin", "last_active_date", "longest_streak_days", "points", "streak_days") ON TABLE "public"."users" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("avatar_object_key", "avatar_url", "created_at", "display_name", "email", "id", "is_admin", "last_active_date", "longest_streak_days", "points", "streak_days") ON TABLE "public"."users" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("avatar_object_key", "avatar_url", "created_at", "display_name", "email", "id", "is_admin", "last_active_date", "longest_streak_days", "points", "streak_days") ON TABLE "public"."users" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("avatar_object_key", "avatar_url", "created_at", "display_name", "email", "id", "is_admin", "last_active_date", "longest_streak_days", "points", "streak_days") ON TABLE "public"."users" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON TABLE "public"."users_self_email" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE SELECT ("email", "id") ON TABLE "public"."users_self_email" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE INSERT ("email", "id") ON TABLE "public"."users_self_email" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE UPDATE ("email", "id") ON TABLE "public"."users_self_email" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE REFERENCES ("email", "id") ON TABLE "public"."users_self_email" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON SEQUENCE "public"."point_events_id_seq" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON SEQUENCE "public"."realtime_subscribe_log_id_seq" FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "private".current_user_is_admin() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "private".get_comment_author_profiles(uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "private".get_my_leaderboard_rank() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "private".list_public_leaderboard(integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".check_feedback_rate_limit() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".check_flag_creation_rate_limit() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".check_flag_rate_limit() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".check_global_anon_rate_limit() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".current_user_can_admin() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".enforce_flag_photos_object_key_guard() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".enforce_flag_status_only_for_non_owner() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".enforce_flag_status_transition() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".enforce_flags_photo_object_key_guard() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".enforce_users_avatar_object_key_guard() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".get_comment_author_profiles(uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".get_my_leaderboard_rank() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_comment_added() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_comment_vote_added() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_dispute_reset() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_insert_history() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_photo_added() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_reopen_reset() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_status_change() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_flag_submitted() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_new_user() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_point_event_streak() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".handle_push_token_updated_at() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".increment_dispute_request(uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".increment_reopen_request(uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".list_public_leaderboard(integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".log_realtime_event(text,text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".notify_flag_status_webhook() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".set_flag_updated_at() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".update_flags_updated_at() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public".verify_webhook_secret(text) FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE ALL ON TABLES FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE ALL ON SEQUENCES FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE ALL ON FUNCTIONS FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public, private, storage REVOKE ALL ON TABLES FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public, private, storage REVOKE ALL ON SEQUENCES FROM PUBLIC, "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public, private, storage REVOKE ALL ON FUNCTIONS FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT DELETE ON TABLE "public"."comment_votes" TO "anon";
GRANT INSERT ON TABLE "public"."comment_votes" TO "anon";
GRANT SELECT ON TABLE "public"."comment_votes" TO "anon";
GRANT UPDATE ON TABLE "public"."comment_votes" TO "anon";
GRANT DELETE ON TABLE "public"."feedback" TO "anon";
GRANT INSERT ON TABLE "public"."feedback" TO "anon";
GRANT SELECT ON TABLE "public"."feedback" TO "anon";
GRANT UPDATE ON TABLE "public"."feedback" TO "anon";
GRANT DELETE ON TABLE "public"."flag_comments" TO "anon";
GRANT INSERT ON TABLE "public"."flag_comments" TO "anon";
GRANT SELECT ON TABLE "public"."flag_comments" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_comments" TO "anon";
GRANT DELETE ON TABLE "public"."flag_edit_history" TO "anon";
GRANT INSERT ON TABLE "public"."flag_edit_history" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_edit_history" TO "anon";
GRANT DELETE ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT INSERT ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT SELECT ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT DELETE ON TABLE "public"."flag_photos" TO "anon";
GRANT INSERT ON TABLE "public"."flag_photos" TO "anon";
GRANT SELECT ON TABLE "public"."flag_photos" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_photos" TO "anon";
GRANT DELETE ON TABLE "public"."flag_status_history" TO "anon";
GRANT INSERT ON TABLE "public"."flag_status_history" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_status_history" TO "anon";
GRANT DELETE ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT INSERT ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT SELECT ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT DELETE ON TABLE "public"."flag_verifications" TO "anon";
GRANT INSERT ON TABLE "public"."flag_verifications" TO "anon";
GRANT SELECT ON TABLE "public"."flag_verifications" TO "anon";
GRANT UPDATE ON TABLE "public"."flag_verifications" TO "anon";
GRANT DELETE ON TABLE "public"."flags" TO "anon";
GRANT INSERT ON TABLE "public"."flags" TO "anon";
GRANT SELECT ON TABLE "public"."flags" TO "anon";
GRANT UPDATE ON TABLE "public"."flags" TO "anon";
GRANT DELETE ON TABLE "public"."notification_preferences" TO "anon";
GRANT INSERT ON TABLE "public"."notification_preferences" TO "anon";
GRANT SELECT ON TABLE "public"."notification_preferences" TO "anon";
GRANT UPDATE ON TABLE "public"."notification_preferences" TO "anon";
GRANT DELETE ON TABLE "public"."point_events" TO "anon";
GRANT INSERT ON TABLE "public"."point_events" TO "anon";
GRANT SELECT ON TABLE "public"."point_events" TO "anon";
GRANT UPDATE ON TABLE "public"."point_events" TO "anon";
GRANT DELETE ON TABLE "public"."push_tokens" TO "anon";
GRANT INSERT ON TABLE "public"."push_tokens" TO "anon";
GRANT SELECT ON TABLE "public"."push_tokens" TO "anon";
GRANT UPDATE ON TABLE "public"."push_tokens" TO "anon";
GRANT DELETE ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT INSERT ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT SELECT ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT UPDATE ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT DELETE ON TABLE "public"."users" TO "anon";
GRANT INSERT ON TABLE "public"."users" TO "anon";
GRANT DELETE ON TABLE "public"."users_self_email" TO "anon";
GRANT INSERT ON TABLE "public"."users_self_email" TO "anon";
GRANT SELECT ON TABLE "public"."users_self_email" TO "anon";
GRANT UPDATE ON TABLE "public"."users_self_email" TO "anon";
GRANT DELETE ON TABLE "public"."comment_votes" TO "authenticated";
GRANT INSERT ON TABLE "public"."comment_votes" TO "authenticated";
GRANT SELECT ON TABLE "public"."comment_votes" TO "authenticated";
GRANT UPDATE ON TABLE "public"."comment_votes" TO "authenticated";
GRANT DELETE ON TABLE "public"."feedback" TO "authenticated";
GRANT INSERT ON TABLE "public"."feedback" TO "authenticated";
GRANT SELECT ON TABLE "public"."feedback" TO "authenticated";
GRANT UPDATE ON TABLE "public"."feedback" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_comments" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_comments" TO "authenticated";
GRANT SELECT ON TABLE "public"."flag_comments" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_comments" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT SELECT ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_photos" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_photos" TO "authenticated";
GRANT SELECT ON TABLE "public"."flag_photos" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_photos" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT SELECT ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT DELETE ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT INSERT ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT SELECT ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT DELETE ON TABLE "public"."flags" TO "authenticated";
GRANT INSERT ON TABLE "public"."flags" TO "authenticated";
GRANT SELECT ON TABLE "public"."flags" TO "authenticated";
GRANT UPDATE ON TABLE "public"."flags" TO "authenticated";
GRANT DELETE ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT INSERT ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT SELECT ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT UPDATE ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT DELETE ON TABLE "public"."point_events" TO "authenticated";
GRANT INSERT ON TABLE "public"."point_events" TO "authenticated";
GRANT SELECT ON TABLE "public"."point_events" TO "authenticated";
GRANT UPDATE ON TABLE "public"."point_events" TO "authenticated";
GRANT DELETE ON TABLE "public"."push_tokens" TO "authenticated";
GRANT INSERT ON TABLE "public"."push_tokens" TO "authenticated";
GRANT SELECT ON TABLE "public"."push_tokens" TO "authenticated";
GRANT UPDATE ON TABLE "public"."push_tokens" TO "authenticated";
GRANT DELETE ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT INSERT ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT SELECT ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT UPDATE ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT DELETE ON TABLE "public"."users" TO "authenticated";
GRANT INSERT ON TABLE "public"."users" TO "authenticated";
GRANT DELETE ON TABLE "public"."users_self_email" TO "authenticated";
GRANT INSERT ON TABLE "public"."users_self_email" TO "authenticated";
GRANT SELECT ON TABLE "public"."users_self_email" TO "authenticated";
GRANT UPDATE ON TABLE "public"."users_self_email" TO "authenticated";
GRANT DELETE ON TABLE "public"."comment_votes" TO "service_role";
GRANT INSERT ON TABLE "public"."comment_votes" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."comment_votes" TO "service_role";
GRANT REFERENCES ON TABLE "public"."comment_votes" TO "service_role";
GRANT SELECT ON TABLE "public"."comment_votes" TO "service_role";
GRANT TRIGGER ON TABLE "public"."comment_votes" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."comment_votes" TO "service_role";
GRANT UPDATE ON TABLE "public"."comment_votes" TO "service_role";
GRANT DELETE ON TABLE "public"."feedback" TO "service_role";
GRANT INSERT ON TABLE "public"."feedback" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."feedback" TO "service_role";
GRANT REFERENCES ON TABLE "public"."feedback" TO "service_role";
GRANT SELECT ON TABLE "public"."feedback" TO "service_role";
GRANT TRIGGER ON TABLE "public"."feedback" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."feedback" TO "service_role";
GRANT UPDATE ON TABLE "public"."feedback" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_comments" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_comments" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_comments" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_comments" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_comments" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_comments" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_comments" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_comments" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_edit_history" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_edit_history_public" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_photos" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_photos" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_photos" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_photos" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_photos" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_photos" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_photos" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_photos" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_status_history" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_status_history" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_status_history" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_status_history" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_status_history" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_status_history" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_status_history" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_status_history" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_status_history_public" TO "service_role";
GRANT DELETE ON TABLE "public"."flag_verifications" TO "service_role";
GRANT INSERT ON TABLE "public"."flag_verifications" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flag_verifications" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flag_verifications" TO "service_role";
GRANT SELECT ON TABLE "public"."flag_verifications" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flag_verifications" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flag_verifications" TO "service_role";
GRANT UPDATE ON TABLE "public"."flag_verifications" TO "service_role";
GRANT DELETE ON TABLE "public"."flags" TO "service_role";
GRANT INSERT ON TABLE "public"."flags" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."flags" TO "service_role";
GRANT REFERENCES ON TABLE "public"."flags" TO "service_role";
GRANT SELECT ON TABLE "public"."flags" TO "service_role";
GRANT TRIGGER ON TABLE "public"."flags" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."flags" TO "service_role";
GRANT UPDATE ON TABLE "public"."flags" TO "service_role";
GRANT DELETE ON TABLE "public"."notification_preferences" TO "service_role";
GRANT INSERT ON TABLE "public"."notification_preferences" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."notification_preferences" TO "service_role";
GRANT REFERENCES ON TABLE "public"."notification_preferences" TO "service_role";
GRANT SELECT ON TABLE "public"."notification_preferences" TO "service_role";
GRANT TRIGGER ON TABLE "public"."notification_preferences" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."notification_preferences" TO "service_role";
GRANT UPDATE ON TABLE "public"."notification_preferences" TO "service_role";
GRANT DELETE ON TABLE "public"."point_events" TO "service_role";
GRANT INSERT ON TABLE "public"."point_events" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."point_events" TO "service_role";
GRANT REFERENCES ON TABLE "public"."point_events" TO "service_role";
GRANT SELECT ON TABLE "public"."point_events" TO "service_role";
GRANT TRIGGER ON TABLE "public"."point_events" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."point_events" TO "service_role";
GRANT UPDATE ON TABLE "public"."point_events" TO "service_role";
GRANT DELETE ON TABLE "public"."push_tokens" TO "service_role";
GRANT INSERT ON TABLE "public"."push_tokens" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."push_tokens" TO "service_role";
GRANT REFERENCES ON TABLE "public"."push_tokens" TO "service_role";
GRANT SELECT ON TABLE "public"."push_tokens" TO "service_role";
GRANT TRIGGER ON TABLE "public"."push_tokens" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."push_tokens" TO "service_role";
GRANT UPDATE ON TABLE "public"."push_tokens" TO "service_role";
GRANT DELETE ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT INSERT ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT REFERENCES ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT SELECT ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT TRIGGER ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT UPDATE ON TABLE "public"."realtime_subscribe_log" TO "service_role";
GRANT DELETE ON TABLE "public"."users" TO "service_role";
GRANT INSERT ON TABLE "public"."users" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."users" TO "service_role";
GRANT REFERENCES ON TABLE "public"."users" TO "service_role";
GRANT SELECT ON TABLE "public"."users" TO "service_role";
GRANT TRIGGER ON TABLE "public"."users" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."users" TO "service_role";
GRANT UPDATE ON TABLE "public"."users" TO "service_role";
GRANT DELETE ON TABLE "public"."users_self_email" TO "service_role";
GRANT INSERT ON TABLE "public"."users_self_email" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."users_self_email" TO "service_role";
GRANT REFERENCES ON TABLE "public"."users_self_email" TO "service_role";
GRANT SELECT ON TABLE "public"."users_self_email" TO "service_role";
GRANT TRIGGER ON TABLE "public"."users_self_email" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."users_self_email" TO "service_role";
GRANT UPDATE ON TABLE "public"."users_self_email" TO "service_role";
GRANT SELECT ("changed_fields") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("created_at") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("flag_id") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("id") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("new_values") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("old_values") ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT SELECT ("created_at") ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT SELECT ("flag_id") ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT SELECT ("from_status") ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT SELECT ("id") ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT SELECT ("to_status") ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT SELECT ("avatar_object_key") ON TABLE "public"."users" TO "authenticated";
GRANT UPDATE ("avatar_object_key") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ("avatar_url") ON TABLE "public"."users" TO "authenticated";
GRANT UPDATE ("avatar_url") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ("created_at") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ("display_name") ON TABLE "public"."users" TO "authenticated";
GRANT UPDATE ("display_name") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ("id") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ("points") ON TABLE "public"."users" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."point_events_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "public"."point_events_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."point_events_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."point_events_id_seq" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."point_events_id_seq" TO "service_role";
GRANT UPDATE ON SEQUENCE "public"."point_events_id_seq" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."point_events_id_seq" TO "service_role";
GRANT SELECT ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "service_role";
GRANT UPDATE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "service_role";
GRANT EXECUTE ON FUNCTION "private".current_user_is_admin() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private".get_comment_author_profiles(p_comment_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private".get_my_leaderboard_rank() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private".list_public_leaderboard(p_limit integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".current_user_can_admin() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".get_comment_author_profiles(p_comment_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".get_my_leaderboard_rank() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".increment_dispute_request(p_flag_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".increment_reopen_request(p_flag_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".list_public_leaderboard(p_limit integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".log_realtime_event(p_event text, p_channel text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public".check_feedback_rate_limit() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".check_flag_creation_rate_limit() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".check_flag_rate_limit() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".check_global_anon_rate_limit() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".enforce_flag_photos_object_key_guard() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".enforce_flag_status_only_for_non_owner() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".enforce_flag_status_transition() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".enforce_flags_photo_object_key_guard() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".enforce_users_avatar_object_key_guard() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_comment_added() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_comment_vote_added() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_dispute_reset() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_insert_history() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_photo_added() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_reopen_reset() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_status_change() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_flag_submitted() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_new_user() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_point_event_streak() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".handle_push_token_updated_at() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".increment_dispute_request(p_flag_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public".increment_reopen_request(p_flag_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public".log_realtime_event(p_event text, p_channel text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public".notify_flag_status_webhook() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".set_flag_updated_at() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".update_flags_updated_at() TO "service_role";
GRANT EXECUTE ON FUNCTION "public".verify_webhook_secret(incoming text) TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT USAGE ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT USAGE ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT EXECUTE ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT DELETE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT INSERT ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT MAINTAIN ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT REFERENCES ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRIGGER ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRUNCATE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT DELETE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT INSERT ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT MAINTAIN ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT REFERENCES ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRIGGER ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRUNCATE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON TABLES TO "service_role";
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_comments"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flag_comments" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_edit_history"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flag_edit_history" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_photos"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flag_photos" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_status_history"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flag_status_history" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flag_verifications"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flag_verifications" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_flags"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_flags" TO "service_role";
  END IF;
END $backup$;
DO $backup$ BEGIN
  IF to_regclass('"public"."bk_2026_08_22_point_links"') IS NOT NULL THEN
    GRANT DELETE ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT INSERT ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT MAINTAIN ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT REFERENCES ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT SELECT ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT TRIGGER ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT TRUNCATE ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
    GRANT UPDATE ON TABLE "public"."bk_2026_08_22_point_links" TO "service_role";
  END IF;
END $backup$;
COMMIT;
