-- PHASE-03A LOCAL CANDIDATE: FDA-012 (partial; managed supabase_admin defaults remain HOLD). NOT AUTHORIZED FOR APPLY.
-- Requires accepted Phase 02 applied + adoption baseline. No production change.
-- Exact order/hashes and outstanding gates are declared in candidate-contract.json.
-- Forward restoration to the pre-03A posture; this restores known weaknesses.
-- Disposable rehearsal only until a separate exact production token authorizes it.
BEGIN;
GRANT MAINTAIN ON TABLE "public"."comment_votes" TO "anon";
GRANT REFERENCES ON TABLE "public"."comment_votes" TO "anon";
GRANT TRIGGER ON TABLE "public"."comment_votes" TO "anon";
GRANT TRUNCATE ON TABLE "public"."comment_votes" TO "anon";
GRANT MAINTAIN ON TABLE "public"."feedback" TO "anon";
GRANT REFERENCES ON TABLE "public"."feedback" TO "anon";
GRANT TRIGGER ON TABLE "public"."feedback" TO "anon";
GRANT TRUNCATE ON TABLE "public"."feedback" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_comments" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_comments" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_comments" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_comments" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history_public" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_edit_history" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_edit_history" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_photos" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_photos" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_photos" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_photos" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_status_history_public" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_status_history" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_status_history" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_status_history" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_status_history" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flag_verifications" TO "anon";
GRANT REFERENCES ON TABLE "public"."flag_verifications" TO "anon";
GRANT TRIGGER ON TABLE "public"."flag_verifications" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flag_verifications" TO "anon";
GRANT MAINTAIN ON TABLE "public"."flags" TO "anon";
GRANT REFERENCES ON TABLE "public"."flags" TO "anon";
GRANT TRIGGER ON TABLE "public"."flags" TO "anon";
GRANT TRUNCATE ON TABLE "public"."flags" TO "anon";
GRANT MAINTAIN ON TABLE "public"."notification_preferences" TO "anon";
GRANT REFERENCES ON TABLE "public"."notification_preferences" TO "anon";
GRANT TRIGGER ON TABLE "public"."notification_preferences" TO "anon";
GRANT TRUNCATE ON TABLE "public"."notification_preferences" TO "anon";
GRANT MAINTAIN ON TABLE "public"."point_events" TO "anon";
GRANT REFERENCES ON TABLE "public"."point_events" TO "anon";
GRANT TRIGGER ON TABLE "public"."point_events" TO "anon";
GRANT TRUNCATE ON TABLE "public"."point_events" TO "anon";
GRANT MAINTAIN ON TABLE "public"."push_tokens" TO "anon";
GRANT REFERENCES ON TABLE "public"."push_tokens" TO "anon";
GRANT TRIGGER ON TABLE "public"."push_tokens" TO "anon";
GRANT TRUNCATE ON TABLE "public"."push_tokens" TO "anon";
GRANT MAINTAIN ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT REFERENCES ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT TRIGGER ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT TRUNCATE ON TABLE "public"."realtime_subscribe_log" TO "anon";
GRANT MAINTAIN ON TABLE "public"."users_self_email" TO "anon";
GRANT REFERENCES ON TABLE "public"."users_self_email" TO "anon";
GRANT TRIGGER ON TABLE "public"."users_self_email" TO "anon";
GRANT TRUNCATE ON TABLE "public"."users_self_email" TO "anon";
GRANT MAINTAIN ON TABLE "public"."users" TO "anon";
GRANT REFERENCES ON TABLE "public"."users" TO "anon";
GRANT TRIGGER ON TABLE "public"."users" TO "anon";
GRANT TRUNCATE ON TABLE "public"."users" TO "anon";
GRANT MAINTAIN ON TABLE "public"."comment_votes" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."comment_votes" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."comment_votes" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."comment_votes" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."feedback" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."feedback" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."feedback" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."feedback" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_comments" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_comments" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_comments" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_comments" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history_public" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_edit_history" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_photos" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_photos" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_photos" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_photos" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_status_history_public" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_status_history" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flag_verifications" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."flags" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."flags" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."flags" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."flags" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."notification_preferences" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."point_events" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."point_events" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."point_events" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."point_events" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."push_tokens" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."push_tokens" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."push_tokens" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."push_tokens" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."realtime_subscribe_log" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."users_self_email" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."users_self_email" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."users_self_email" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."users_self_email" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."users" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."users" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."users" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."users" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."point_events_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."point_events_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."realtime_subscribe_log_id_seq" TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT DELETE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT INSERT ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT REFERENCES ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRIGGER ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRUNCATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT USAGE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT DELETE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT INSERT ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT REFERENCES ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRIGGER ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT TRUNCATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT SELECT ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "public" GRANT USAGE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT EXECUTE ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT DELETE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT INSERT ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT REFERENCES ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRIGGER ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRUNCATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT USAGE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT EXECUTE ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT DELETE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT INSERT ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT REFERENCES ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRIGGER ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT TRUNCATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT SELECT ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT UPDATE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "storage" GRANT USAGE ON SEQUENCES TO "authenticated";
COMMIT;
