/**
 * PHASE-02A — the canonical migration lineage cannot drift silently.
 *
 * ─── WHAT WENT WRONG BEFORE ───────────────────────────────────────────────
 * Build 33 reorganised supabase/ into the layout Supabase actually applies:
 * `migrations/` for the managed lineage, `nonmanaged/` for proposals, hand-run
 * history, drift captures and destructive data. Nothing enforced that split,
 * and EIGHT guard suites went on reading pre-reorganisation paths. They did not
 * fail loudly — they died at module load, so every summary counted them as
 * suites while they asserted nothing at all. One carried a frozen content hash
 * that had been superseded months earlier and could not report it.
 *
 * These tests make the lineage self-describing, so the next reorganisation
 * fails here instead of quietly disarming coverage somewhere else.
 *
 * PRODUCTION IS NEVER CONTACTED. The ledger is read from the committed
 * crosswalk, which was captured read-only and is regenerated by
 * scripts/generate-migration-crosswalk.mjs.
 */
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';
import fs from 'fs';
import path from 'path';

const ROOT = path.join(__dirname, '..', '..');
const MIGRATIONS = path.join(ROOT, 'supabase', 'migrations');
const NONMANAGED = path.join(ROOT, 'supabase', 'nonmanaged');
const crosswalk = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'supabase', 'contract', 'migration-crosswalk.v1.json'), 'utf8'),
) as {
  rules: { ledgerHead: string };
  summary: Record<string, number>;
  entries: {
    version: string;
    status: string;
    file?: string;
    slug?: string;
    sha256?: string;
    ledgerName?: string;
  }[];
};

const managedFiles = fs.readdirSync(MIGRATIONS).filter((n) => n.endsWith('.sql'));
const NAME_RE = /^(\d{14})_(.+)\.sql$/;

describe('PHASE-02A — managed migration lineage', () => {
  it('every managed file is <14-digit version>_<slug>.sql', () => {
    const malformed = managedFiles.filter((n) => !NAME_RE.test(n));
    expect(`malformed: ${malformed.join(', ') || 'none'}`).toBe('malformed: none');
  });

  it('no two managed files share a version', () => {
    const seen = new Map<string, string[]>();
    for (const n of managedFiles) {
      const v = NAME_RE.exec(n)![1];
      seen.set(v, [...(seen.get(v) ?? []), n]);
    }
    const dupes = [...seen.entries()].filter(([, v]) => v.length > 1);
    expect(
      `duplicate versions: ${dupes.map(([v, f]) => `${v} (${f.join(' + ')})`).join('; ') || 'none'}`,
    ).toBe('duplicate versions: none');
  });

  it('every version production applied still has its source file, byte for byte', () => {
    // Applied migrations are immutable history. Editing one makes the repo
    // unable to reproduce what production actually ran.
    const drifted: string[] = [];
    for (const e of crosswalk.entries) {
      if (e.status !== 'APPLIED' || !e.file || !e.sha256) continue;
      const full = path.join(ROOT, e.file);
      if (!fs.existsSync(full)) {
        drifted.push(`${e.version}: file deleted`);
        continue;
      }
      const actual = createHash('sha256').update(fs.readFileSync(full)).digest('hex');
      if (actual !== e.sha256) drifted.push(`${e.version}: content changed`);
    }
    expect(`applied-file drift: ${drifted.join('; ') || 'none'}`).toBe('applied-file drift: none');
  });

  it('every applied file is byte-identical to its blob in the immutable Build 33 commit', () => {
    // W2 (independent review): the hash test above compares each file to a
    // sha256 stored in the crosswalk — which is REGENERATED from that same
    // mutable file. Editing an applied migration and re-running
    // `npm run contract:crosswalk` launders the change past both. That is a
    // plausible accident, not just malice: anyone adding a new migration
    // regenerates, and a concurrent edit rides along silently.
    //
    // Build 33 (f5594171) is the submitted binary's source and cannot change.
    // Pinning against its git objects is an EXTERNAL reference that
    // regeneration cannot touch.
    const BUILD33 = 'f5594171e75bc5ec92a87d0392c361601ddedfba';
    let haveObject = true;
    try {
      execFileSync('git', ['cat-file', '-e', `${BUILD33}^{commit}`], {
        cwd: ROOT,
        stdio: 'ignore',
      });
    } catch {
      haveObject = false;
    }
    // Never let an environment limitation read as a pass. CI checks out with
    // fetch-depth: 0 precisely so this object is present.
    expect(`Build 33 object available: ${haveObject}`).toBe('Build 33 object available: true');

    const drifted: string[] = [];
    for (const e of crosswalk.entries) {
      if (e.status !== 'APPLIED' || !e.file || !e.sha256) continue;
      let blob: Buffer;
      try {
        blob = execFileSync('git', ['cat-file', '-p', `${BUILD33}:${e.file}`], {
          cwd: ROOT,
          maxBuffer: 32 * 1024 * 1024,
        });
      } catch {
        drifted.push(`${e.version}: absent at Build 33`);
        continue;
      }
      if (createHash('sha256').update(blob).digest('hex') !== e.sha256) {
        drifted.push(`${e.version}: differs from Build 33`);
      }
    }
    expect(`applied files diverging from Build 33: ${drifted.join('; ') || 'none'}`).toBe(
      'applied files diverging from Build 33: none',
    );
  });

  it('every applied version has exactly one source record', () => {
    expect(crosswalk.summary.appliedWithoutSource).toBe(0);
    expect(crosswalk.summary.appliedInLedger).toBe(71);
    expect(crosswalk.rules.ledgerHead).toBe('20260830130000');
  });

  it('no NEW migration is backdated at or before the ledger head', () => {
    // Six unapplied files already sit before the head; they are recorded and
    // frozen. A seventh would be a fresh ordering hazard: `supabase db push`
    // resolves by version, so a backdated file applies out of sequence.
    const KNOWN_BACKDATED = [
      '20260818211920', // reconcile_oob_grant_select_is_admin_for_replay_20260829
      '20260828040000', // mod1_moderation_release_safety
      '20260828050000', // mod1_admin_report_queue
      '20260828060000', // mod1r_fix1_report_and_insert_authz
      '20260828070000', // mod1r_fix1_pending_close_state
      '20260828080000', // mod1r_fix2_action_intent
    ];
    const backdated = crosswalk.entries
      .filter((e) => e.status === 'UNAPPLIED_BACKDATED')
      .map((e) => e.version);
    expect(backdated.sort()).toEqual(KNOWN_BACKDATED.sort());
  });

  it('the crosswalk ledger matches the independent evidence capture', () => {
    // W3 (independent review): `--check` regenerates the ledger from the very
    // file it is checking, so a self-consistent forgery — dropping an applied
    // version and letting every derived field recompute — passes it. The
    // read-only capture committed alongside is a SECOND, independent record of
    // the same 71 rows. Comparing them is what makes the ledger falsifiable.
    const evidence = fs
      .readFileSync(
        path.join(
          ROOT,
          'qa-reports',
          '2026-09-03_Phase02_ContractTruth',
          'evidence',
          'applied-versions.txt',
        ),
        'utf8',
      )
      .split('\n')
      .filter(Boolean)
      .map((line) => {
        const [version, ...rest] = line.trim().split(' ');
        return { version, name: rest.join(' ') };
      });

    const fromCrosswalk = crosswalk.entries
      .filter((e) => e.ledgerName !== undefined)
      .map((e) => ({ version: e.version, name: e.ledgerName! }));

    expect(`evidence rows: ${evidence.length}`).toBe('evidence rows: 71');
    expect(fromCrosswalk.map((e) => e.version).sort()).toEqual(
      evidence.map((e) => e.version).sort(),
    );
    const nameMismatch = evidence.filter(
      (e) => fromCrosswalk.find((c) => c.version === e.version)?.name !== e.name,
    );
    expect(
      `ledger name mismatches vs evidence: ${nameMismatch.map((e) => e.version).join(', ') || 'none'}`,
    ).toBe('ledger name mismatches vs evidence: none');
  });

  it('the committed crosswalk matches the tree', () => {
    const recorded = new Set(
      crosswalk.entries.filter((e) => e.file).map((e) => path.basename(e.file!)),
    );
    const missing = managedFiles.filter((n) => !recorded.has(n));
    expect(`unrecorded managed files: ${missing.join(', ') || 'none'}`).toBe(
      'unrecorded managed files: none',
    );
  });
});

describe('PHASE-02A — nonmanaged stays out of the applied lineage', () => {
  it('destructive data scripts never appear in supabase/migrations', () => {
    const destructive = fs.readdirSync(path.join(NONMANAGED, 'destructive-data'));
    const leaked = destructive.filter((n) =>
      managedFiles.some((m) => m.endsWith(n) || m.includes(n.replace(/^\d{4}-\d{2}-\d{2}_/, ''))),
    );
    expect(`destructive scripts in managed lineage: ${leaked.join(', ') || 'none'}`).toBe(
      'destructive scripts in managed lineage: none',
    );
  });

  it('each nonmanaged area exists and is documented', () => {
    const areas = [
      'destructive-data',
      'live-out-of-band',
      'manual',
      'proposed',
      'rollback-recovery',
    ];
    for (const area of areas) {
      expect(`${area} exists: ${fs.existsSync(path.join(NONMANAGED, area))}`).toBe(
        `${area} exists: true`,
      );
    }
    const provenance = fs.readFileSync(path.join(NONMANAGED, 'PROVENANCE.md'), 'utf8');
    for (const area of areas) {
      expect(`PROVENANCE.md covers ${area}: ${provenance.includes(area)}`).toBe(
        `PROVENANCE.md covers ${area}: true`,
      );
    }
  });

  it('guards read migration SQL from the directory that actually holds it', () => {
    // The exact regression that killed eight suites: a test naming
    // supabase/migrations/ for a file that lives under nonmanaged/.
    const testFiles: string[] = [];
    const walk = (dir: string) => {
      if (!fs.existsSync(dir)) return;
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (/\.test\.(tsx?|jsx?|mjs)$/.test(entry.name)) testFiles.push(full);
      }
    };
    // W4 (independent review): this walked only src/, so the root-level
    // __tests__ and scripts/__tests__ suites were never scanned, and the
    // .tsx?-only filter skipped .test.js/.mjs. No offenders live there today —
    // closing it while it is empty is the cheap moment.
    for (const dir of ['src', '__tests__', 'scripts']) walk(path.join(ROOT, dir));

    const offenders: string[] = [];
    for (const file of testFiles) {
      const body = fs.readFileSync(file, 'utf8');
      // Literal filenames attributed to supabase/migrations/, in either the
      // slash form or the path.join(...) form.
      const matches = [
        ...body.matchAll(/supabase\/migrations\/([A-Za-z0-9_.-]+\.sql)/g),
        ...body.matchAll(/'supabase',\s*'migrations',\s*'([A-Za-z0-9_.-]+\.sql)'/g),
      ];
      for (const match of matches) {
        const name = match[1];
        if (managedFiles.includes(name)) continue;
        // Evaluate the line the match is ON, not the first line that happens to
        // mention the filename — the same name can appear both as a current
        // nonmanaged path and as a historical one a few lines apart.
        const line = body.slice(0, match.index ?? 0).split('\n').length - 1;
        const text = body.split('\n')[line] ?? '';
        // A historical `git show <sha>:<path>` read is legitimate: the file WAS
        // at that path in that commit, and rewriting it breaks the read.
        //
        // W1 (independent review): this was /git|show|APPROVED_BASE/ against the
        // whole line — an unanchored substring test that ANY line containing
        // "git", "show", or even "digit" satisfied. A comment reading
        // "// 14-digit version" disarmed the guard for that line. Now the line
        // must actually name a pinned base ref or a literal `git show`, which
        // exactly one line in src/ does today.
        if (/APPROVED_BASE|['"`]show['"`]|\bgit\s+show\b/.test(text)) continue;
        offenders.push(`${path.relative(ROOT, file)}:${line + 1} -> ${name}`);
      }
    }
    expect(`tests reading absent managed migrations: ${offenders.join('; ') || 'none'}`).toBe(
      'tests reading absent managed migrations: none',
    );
  });
});
